name: Build Batocera For TXCZ-RK3128-V3.1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Batocera for txcz-rk3128-v3.1
    steps:
      - name: Before freeing up disk space
        run: |
          echo "Before freeing up disk space"
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="

      - name: "Optimize Disk Space"
        uses: "hugoalh/disk-space-optimizer-ghaction@v0.8.1"
        with:
          operate_sudo: "True"
          general_include: ".+"
          general_exclude: |-
            ^GCC$
            ^G\+\+$
            Clang
            LLVM
          docker_include: ".+"
          docker_prune: "True"
          docker_clean: "True"
          apt_prune: "True"
          apt_clean: "True"
          homebrew_prune: "True"
          homebrew_clean: "True"
          npm_prune: "True"
          npm_clean: "True"
          os_swap: "True"

      - name: Freeing up disk space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 3072
          swap-size-mb: 1
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"

      - name: Free up disk space complete
        run: |
          echo "Free up disk space complete"
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="
        
      - name: 下载编译所需的依赖 (Install the software packages required for compilation)
        run: |
          sudo apt update

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: batocera41-txcz-rk3128-v3-1
          submodules: recursive
          fetch-depth: 1

      - name: Move Docker data-root
        run: |
          sudo systemctl stop docker
          sudo mkdir -p /home/runner/work/batocera.linux/batocera.linux/docker-data
          echo '{
            "data-root": "/home/runner/work/batocera.linux/batocera.linux/docker-data"
          }' | sudo tee /etc/docker/daemon.json
          sudo systemctl start docker
          docker info | grep "Docker Root Dir"          

      - name: Check CI
        run: |
          echo $CI

      - name: Check Makefile
        run: |
          grep -n "DOCKER_TTY" Makefile

      - name: Build docker image
        run: |
          docker build \
            -t batoceralinux/batocera.linux-build:latest \
            .

      - name: Check directories
        run: |
          pwd
          df -h
          ls -ld .
          ls -ld output || true
          realpath output || true

      - name: Check Make vars
        run: |
          make vars

      - name: Check root usage
        run: |
          echo "==== / ===="
          sudo du -xh --max-depth=1 / 2>/dev/null | sort -h

          echo
          echo "==== /var ===="
          sudo du -xh --max-depth=2 /var 2>/dev/null | sort -h | tail -30

          echo
          echo "==== docker ===="
          sudo du -sh /var/lib/docker 2>/dev/null || true

          echo
          echo "==== new docker ===="
          du -sh docker-data 2>/dev/null || true

      - name: Build Batocera
        run: |
          make rk3128-build

      - name: Check build output
        run: |
          ls -lh output/rk3128/images/batocera/images/txcz-rk3128-v3-1/
  
      - name: Upload Batocera image
        uses: actions/upload-artifact@v4
        with:
          name: batocera-rk3128-txcz-rk3128-v3-1-image
          path: |
            output/rk3128/images/batocera/images/txcz-rk3128-v3-1/*.img.gz
          retention-days: 7